name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  validate-monitors:
    name: Validate monitors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate monitors
        run: scripts/Test-Monitors.ps1
        shell: pwsh
