name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  DD_APP_KEY: ${{ secrets.DD_APP_KEY }}

jobs:
  validate-monitors:
    name: Validate monitors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate monitors
        run: scripts/Test-Monitors.ps1
        shell: pwsh
