name: Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  DD_APP_KEY: ${{ secrets.DD_APP_KEY }}

jobs:
  publish-monitors:
    name: Publish monitors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish monitors
        run: scripts/Publish-Monitors.ps1
        shell: pwsh
